Markdown & read me
Legal-Innovation-Lab-Wales/dev-page pull request #1
Opened 2021-06-15 09:48 UTC by AlexW555

Added a markdown blog post example & Initialised a read-me for the project

Let me know of any changes 😊

2021-06-15 13:15 UTC, IeuanSkinner approved these changes
LGTM

2021-06-15 13:19 UTC, phil-6 commented on _data/blog-posts.yml
> +  publish-date: June 1
should be date when we merge this

2021-06-15 13:20 UTC, phil-6 requested changes
I've proof'd your blog post in the word doc. I love the content but a few grammatical and structural change suggestions (with tracked changes on)

2021-06-16 07:16 UTC, phil-6 approved these changes

2021-06-17 12:47 UTC, merged